---------------------------
-----------CASO 1----------
---------------------------

SELECT * FROM ALUMNO;

SELECT CARRERAID "INDENTIFICACION DE LA CARRERA",
COUNT(ALUMNOID) "TOTAL ALUMNOS MATRICULADOS",
'Le corresponden '||TO_CHAR(30200 * COUNT(ALUMNOID), '$999G999')||' del presupuesto asignado para publicidad.' "MONTO POR PUBLICIDAD"
FROM ALUMNO
GROUP BY CARRERAID
ORDER BY "TOTAL ALUMNOS MATRICULADOS" DESC;

---------------------------
-----------CASO 2----------
---------------------------

SELECT * FROM ALUMNO;

SELECT CARRERAID "CARRERA",
COUNT(ALUMNOID) "TOTAL DE ALUMNOS"
FROM ALUMNO
GROUP BY CARRERAID
HAVING COUNT(ALUMNOID) > 4
ORDER BY CARRERAID;

---------------------------
-----------CASO 3----------
---------------------------

SELECT * FROM EMPLEADO;

SELECT TO_CHAR(RUN_JEFE, '99G999G999') "RUN JEFE SIN DV",
COUNT(RUN_EMP) "TOTAL DE EMPLEADOS A SU CARGO", 
TO_CHAR(MAX(SALARIO), '99G999G999') "SALARIO MAXIMO",
(COUNT(RUN_EMP) * 10)||'% del Salario Máximo' "PORCENTAJE DE BONIFICACION",
TO_CHAR(MAX(SALARIO) * (COUNT(RUN_EMP)/100), '$999G999') "BONIFICACION"
FROM EMPLEADO
WHERE RUN_JEFE IS NOT NULL
GROUP BY RUN_JEFE
ORDER BY "TOTAL DE EMPLEADOS A SU CARGO";

---------------------------
-----------CASO 4----------
---------------------------

SELECT * FROM ESCOLARIDAD_EMP;
SELECT * FROM EMPLEADO;

SELECT ID_ESCOLARIDAD "ESCOLARIDAD",
CASE ID_ESCOLARIDAD
WHEN 20 THEN 'MEDIA CIENTÍFICA HUMANISTA'
WHEN 30 THEN 'MEDIA TÉCNICO PROFESIONAL'
WHEN 40 THEN 'SUPERIOR CENTRO DE FORMACIÓN TÉCNICA'
WHEN 50 THEN 'SUPERIOR INSTITUTO PROFESIONAL'
WHEN 60 THEN 'SUPERIOR UNIVERSIDAD'
ELSE 'BÁSICA' 
END "DESCRIPCIÓN ESCOLARIDAD",
COUNT(RUN_EMP) "TOTAL DE EMPLEADOS",
TO_CHAR(ROUND(MAX(SALARIO)), '$9G999G999') "SALARIO MAXIMO",
TO_CHAR(ROUND(MIN(SALARIO)), '$9G999G999') "SALARIO MINIMO",
TO_CHAR(ROUND(SUM(SALARIO)), '$9G999G999') "SALARIO TOTAL",
TO_CHAR(ROUND(AVG(SALARIO)), '$9G999G999') "SALARIO PROMEDIO"
FROM EMPLEADO
GROUP BY ID_ESCOLARIDAD
ORDER BY "TOTAL DE EMPLEADOS" DESC;

---------------------------
-----------CASO 5----------
---------------------------

SELECT * FROM PRESTAMO;

SELECT TITULOID "CODIGO DEL LIBRO",
COUNT(RUN_EMP) "TOTAL DE VECES SOLICITADO",
CASE
WHEN COUNT(RUN_EMP) = 1 THEN 'No se requiere comprar nuevos ejemplares'
WHEN COUNT(RUN_EMP) BETWEEN 2 AND 3 THEN 'Se requiere comprar 1 nuevo ejemplar'
WHEN COUNT(RUN_EMP) BETWEEN 4 AND 5 THEN 'Se requiere comprar 2 nuevos ejemplares'
ELSE 'Se requiere comprar 4 nuevos ejemplares'
END "           SUGERENCIA"
FROM PRESTAMO
WHERE EXTRACT(YEAR FROM FECHA_INI_PRESTAMO) = EXTRACT(YEAR FROM SYSDATE) - 1
GROUP BY TITULOID
ORDER BY "TOTAL DE VECES SOLICITADO" DESC;

---------------------------
-----------CASO 6----------
---------------------------

SELECT * FROM PRESTAMO;

SELECT TO_CHAR(RUN_EMP, '99G999G999') "RUN EMPLEADO",
TO_CHAR(FECHA_INI_PRESTAMO, 'MM/YYYY') "MES PRESTAMOS LIBROS",
COUNT(PRESTAMOID) "TOTAL PRESTAMOS ATENDIDOS",
TO_CHAR(COUNT(PRESTAMOID)*10000, '$99,999') "ASIGNACION POR PRESTAMOS"
FROM PRESTAMO
WHERE EXTRACT(YEAR FROM FECHA_INI_PRESTAMO) = EXTRACT(YEAR FROM SYSDATE) - 1
GROUP BY RUN_EMP, TO_CHAR(FECHA_INI_PRESTAMO, 'MM/YYYY')
HAVING COUNT(PRESTAMOID) > 2
ORDER BY "MES PRESTAMOS LIBROS", "ASIGNACION POR PRESTAMOS" DESC, "RUN EMPLEADO" DESC;


