--Requerimiento 1

ALTER SESSION SET CONTAINER = XEPDB1;

----Gestion del Perfil y su Contraseña----

CREATE PROFILE PERFIL_KOPERA LIMIT
    FAILED_LOGIN_ATTEMPTS       5  
    PASSWORD_LOCK_TIME          1/24  
    PASSWORD_LIFE_TIME          180    
    PASSWORD_GRACE_TIME         7          
    PASSWORD_REUSE_TIME         365        
    PASSWORD_REUSE_MAX          5          
    PASSWORD_VERIFY_FUNCTION    ORA12C_STRONG_VERIFY_FUNCTION;


DROP USER BDY1102_P9_1;
DROP USER BDY1102_P9_2;
DROP USER BDY1102_P9_3;
DROP USER BDY1102_P9_4;
DROP USER BDY1102_P9_5;
DROP USER BDY1102_P9_6;

----Creacion de Usuarios-----

CREATE USER BDY1102_P9_1
    IDENTIFIED BY "KoPera2024##Aa"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS
    PROFILE PERFIL_KOPERA
    ACCOUNT UNLOCK;

CREATE USER BDY1102_P9_2
    IDENTIFIED BY "KoPera2024##Bb"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS
    PROFILE PERFIL_KOPERA
    ACCOUNT UNLOCK;

CREATE USER BDY1102_P9_3
    IDENTIFIED BY "KoPera2024##Cc"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA 100M ON USERS
    PROFILE PERFIL_KOPERA
    ACCOUNT UNLOCK;

CREATE USER BDY1102_P9_4
    IDENTIFIED BY "KoPera2024##Dd"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA 100M ON USERS
    PROFILE PERFIL_KOPERA
    ACCOUNT UNLOCK;

CREATE USER BDY1102_P9_5
    IDENTIFIED BY "KoPera2024##Ee"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA 100M ON USERS
    PROFILE PERFIL_KOPERA
    ACCOUNT UNLOCK;

CREATE USER BDY1102_P9_6
    IDENTIFIED BY "KoPera2024##Ff"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA 100M ON USERS
    PROFILE PERFIL_KOPERA
    ACCOUNT UNLOCK;

--- Asignación de Privilegios ---

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE,
      CREATE VIEW, CREATE SYNONYM, CREATE PROCEDURE
    TO BDY1102_P9_1;

GRANT CREATE SESSION, CREATE VIEW, CREATE SYNONYM
    TO BDY1102_P9_2;

GRANT CREATE SESSION, CREATE VIEW, CREATE SYNONYM
    TO BDY1102_P9_3;

GRANT CREATE SESSION TO BDY1102_P9_4;
GRANT CREATE SESSION TO BDY1102_P9_5;
GRANT CREATE SESSION TO BDY1102_P9_6;

--- Gestion de Roles ---
CREATE ROLE ROL_DESARROLLADOR_KOPERA;    
CREATE ROLE ROL_REPORTES_TRANSACCIONES;  
CREATE ROLE ROL_REPORTES_CLIENTES;       

--- Asignacion de Privilegios a Roles ---

GRANT SELECT ON APORTE_A_SBIF             TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON PRODUCTO_INVERSION        TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON CREDITO                   TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON TIPO_CONTRATO             TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON REGION                    TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON PROVINCIA                 TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON COMUNA                    TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON SUCURSAL                  TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON PROFESION_OFICIO          TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON TIPO_MOVIMIENTO           TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON FORMA_PAGO                TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON CLIENTE                   TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON PRODUCTO_INVERSION_CLIENTE TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON MOVIMIENTO                TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON CREDITO_CLIENTE           TO ROL_DESARROLLADOR_KOPERA;
GRANT SELECT ON CUOTA_CREDITO_CLIENTE     TO ROL_DESARROLLADOR_KOPERA;

GRANT INSERT, UPDATE, DELETE ON CREDITO_CLIENTE            TO ROL_DESARROLLADOR_KOPERA;
GRANT INSERT, UPDATE, DELETE ON PRODUCTO_INVERSION_CLIENTE TO ROL_DESARROLLADOR_KOPERA;
GRANT INSERT, UPDATE, DELETE ON CUOTA_CREDITO_CLIENTE      TO ROL_DESARROLLADOR_KOPERA;


GRANT SELECT ON TIPO_MOVIMIENTO TO ROL_REPORTES_TRANSACCIONES;
GRANT SELECT ON SUCURSAL        TO ROL_REPORTES_TRANSACCIONES;
GRANT SELECT ON TIPO_CONTRATO   TO ROL_REPORTES_TRANSACCIONES;
GRANT SELECT ON CLIENTE         TO ROL_REPORTES_TRANSACCIONES;
GRANT SELECT ON REGION          TO ROL_REPORTES_TRANSACCIONES;
GRANT SELECT ON PROVINCIA       TO ROL_REPORTES_TRANSACCIONES;
GRANT SELECT ON COMUNA          TO ROL_REPORTES_TRANSACCIONES;


GRANT SELECT ON CLIENTE   TO ROL_REPORTES_CLIENTES;
GRANT SELECT ON REGION    TO ROL_REPORTES_CLIENTES;
GRANT SELECT ON PROVINCIA TO ROL_REPORTES_CLIENTES;
GRANT SELECT ON COMUNA    TO ROL_REPORTES_CLIENTES;

GRANT ROL_DESARROLLADOR_KOPERA   TO BDY1102_P9_2;
GRANT ROL_DESARROLLADOR_KOPERA   TO BDY1102_P9_3;
GRANT ROL_REPORTES_TRANSACCIONES TO BDY1102_P9_4;
GRANT ROL_REPORTES_CLIENTES      TO BDY1102_P9_5;
GRANT ROL_REPORTES_CLIENTES      TO BDY1102_P9_6;

--- Asignacion de Nombres Alternativos por Objetos ---

CREATE PUBLIC SYNONYM SIN_APORTE_SBIF          FOR BDY1102_P9_1.APORTE_A_SBIF;
CREATE PUBLIC SYNONYM SIN_PROD_INVERSION        FOR BDY1102_P9_1.PRODUCTO_INVERSION;
CREATE PUBLIC SYNONYM SIN_CREDITO               FOR BDY1102_P9_1.CREDITO;
CREATE PUBLIC SYNONYM SIN_TIPO_CONTRATO         FOR BDY1102_P9_1.TIPO_CONTRATO;
CREATE PUBLIC SYNONYM SIN_REGION                FOR BDY1102_P9_1.REGION;
CREATE PUBLIC SYNONYM SIN_PROVINCIA             FOR BDY1102_P9_1.PROVINCIA;
CREATE PUBLIC SYNONYM SIN_COMUNA                FOR BDY1102_P9_1.COMUNA;
CREATE PUBLIC SYNONYM SIN_SUCURSAL              FOR BDY1102_P9_1.SUCURSAL;
CREATE PUBLIC SYNONYM SIN_PROFESION_OFICIO      FOR BDY1102_P9_1.PROFESION_OFICIO;
CREATE PUBLIC SYNONYM SIN_TIPO_MOVIMIENTO       FOR BDY1102_P9_1.TIPO_MOVIMIENTO;
CREATE PUBLIC SYNONYM SIN_FORMA_PAGO            FOR BDY1102_P9_1.FORMA_PAGO;
CREATE PUBLIC SYNONYM SIN_CLIENTE               FOR BDY1102_P9_1.CLIENTE;
CREATE PUBLIC SYNONYM SIN_PROD_INV_CLIENTE      FOR BDY1102_P9_1.PRODUCTO_INVERSION_CLIENTE;
CREATE PUBLIC SYNONYM SIN_MOVIMIENTO            FOR BDY1102_P9_1.MOVIMIENTO;
CREATE PUBLIC SYNONYM SIN_CREDITO_CLIENTE       FOR BDY1102_P9_1.CREDITO_CLIENTE;
CREATE PUBLIC SYNONYM SIN_CUOTA_CREDITO_CLIENTE FOR BDY1102_P9_1.CUOTA_CREDITO_CLIENTE;

--Requerimiento 2

-- Crear nueva base de datos con 
--  Nombre: BDY1102_P9_3 
--  Usuario: BDY1102_P9_3 
--  Contraseña: KoPera2024##Cc
--  Nombre del Servicio: XEPDB1

--Ejecutar desde system
CREATE OR REPLACE VIEW V_TOTAL_CREDITOS_CLIENTE AS
SELECT C.NUMRUN || '-' || C.DVRUN "RUN CLIENTE",
INITCAP(C.PNOMBRE || ' ' || C.SNOMBRE || ' ' || C.APPATERNO || ' ' || C.APMATERNO) "NOMBRE CLIENTE",
COUNT(*) "CREDITOS SOLICITADOS"
FROM CLIENTE C JOIN CREDITO_CLIENTE CC ON(C.NRO_CLIENTE = CC.NRO_CLIENTE)
GROUP BY C.NUMRUN, C.DVRUN, C.PNOMBRE, C.SNOMBRE, C.APPATERNO, C.APMATERNO;
COMMIT;

GRANT SELECT ON V_TOTAL_CREDITOS_CLIENTE TO BDY1102_P9_3;

--Ejecutar desde BDY1102_P9_3
SELECT * FROM SYSTEM.V_TOTAL_CREDITOS_CLIENTE;


--  Nombre: BDY1102_P9_4 
--  Usuario: BDY1102_P9_4 
--  Contraseña: KoPera2024##Dd
--  Nombre del Servicio: XEPDB1

--Ejecutar desde System
CREATE OR REPLACE VIEW V_DATOS_CLIENTES AS
SELECT TO_CHAR(C.NUMRUN, '09G999G999') || '-' || C.DVRUN "RUN CLIENTE",
INITCAP(C.PNOMBRE || ' ' || C.SNOMBRE || ' ' || C.APPATERNO || ' ' || C.APMATERNO) "NOMBRE CLIENTE",
C.DIRECCION "Direccion Cliente" FROM CLIENTE C;
COMMIT;

--Ejecutar desde BDY1102_P9_4
GRANT SELECT ON V_DATOS_CLIENTES TO BDY1102_P9_4;

SELECT * FROM SYSTEM.V_DATOS_CLIENTES;
